<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\InstrumentHistory;

/**
 * InstrumentHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstrumentHistoryRepository extends EntityRepository
{
    public function findData($date, $file)
    {
        //$conn = $this->getEntityManager()->getConnection();
        /*$statement = $conn->prepare("select instrument_id from instrument_history where date = '$date' and instrument_id in (select id from instrument where file_name = '$file')");
        $statement->execute();
        $result = ($statement->fetchAll()) ? true : false;
        if($result) {
            return true;
        }*/
        $em = $this->getEntityManager();
        $query = $em->createQuery('
        select i.instrumentId from AppBundle:InstrumentHistory i
        where i.date = :date and i.instrumentId 
        in (select n.id from AppBundle:Instrument n where n.file_name = :file)
    ')
            ->setParameter('date', $date)
            ->setParameter('file', $file);

        $products = $query->getResult();
        exit;
    }
}
