  # index:
  #  path: /
  #  controller: App\Controller\MainController::index

lucky_number:
    path:     /find
    controller: App\Controller\MainController::lucky

find_max:
    path:       /user/?max={max}
    controller: App\Controller\UserController::max
    methods:    GET|HEAD

login:
    path:       /userLogin
    controller: App\Controller\UserController::login

register:
    path:       /userRegister  
    controller: App\Controller\UserController::register

update:
    path:       /update/{id} 
    controller: App\Controller\UserController::update

list:
    path:       /project 
    controller: App\Controller\UserController::list

getMainCategory:
    path:       /category 
    controller: App\Controller\MainController::getMainCategory

getSubCategory:
    path:       /getSubCategory 
    controller: App\Controller\MainController::getSubCategory

getProducts:
    path:       /getproduct 
    controller: App\Controller\MainController::getproduct

chart:
    path:       /chart 
    controller: App\Controller\MainController::chart

userlist:
    path:       /user/list/{page}/
    controller: App\Controller\UserController::getUserDetails

logoutSession:
    path:       /userLogout
    controller: App\Controller\UserController::logout